### PR TITLE
Require API key when recording data

### PR DESCRIPTION
**Pull request by Abbondanzo**
This adds a fourth argument to the `record` mutation which is an API key that gets read from the root of the repo. I wasn't able to get localproxy working on WSL to test out the server's response, but the probe passes the argument over correctly

### CODE REVIEW

**Comment by kj800x** [comment]
:bread-secured: Thanks Pete! I'll pull it down when I get back to a computer.

Eventually I want to make localproxy client spin up a standalone server if it detects that the server isn't installed, which probably would be a pretty good change for if anyone other than me wants to run this 😅

**Comment by kj800x** [comment]
@Abbondanzo Actually super curious.... What error message do you run into when you try to stand up the server?

I ran `apt-get purge localproxy` and `rm -rf /etc/localproxy` which should get me pretty close to a blank slate and the server was able to turn on (just with warnings). I'm able to get to graphql-playground if I go directly to the url that it prints out: http://localhost:35327/temp/graphql. I'm just wondering if there's something else to fix for the graceful fallback. 

```
kevin@raikou:~/src/temp/server$ bend

> temp-monitor-server@ start /home/kevin/src/temp/server
> npm run build && node lib/migrations/runMigrations.js && node lib/server.js


> temp-monitor-server@ build /home/kevin/src/temp/server
> tsc --build && copyfiles -u 1 src/**/*.sql lib/

⛔ Failed to write localproxy file,
   are you a member of localproxyusers?
💡 Try running "sudo usermod -a -G localproxyusers $USER"
   and then restarting your login session.

(node:137346) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/etc/localproxy/sites/temp-station.json'
(Use `node --trace-warnings ...` to show where the warning was created)
(node:137346) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:137346) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[16:30:55] INFO: 🚀 Server at http://localhost:35327/temp/graphql
[16:30:55] INFO: 🚀 Subscriptions at ws://localhost:35327/temp/graphql
```

**Comment by Abbondanzo** [comment]
I had a very similar error due to permissions, but I resolved it after running `chown -R myhostname:localproxyusers /etc/localproxy`:
```
> tsc --build && copyfiles -u 1 src/**/*.sql lib/

⛔ Failed to clean up an existing localproxy file,
   are you a member of localproxyusers?
💡 Try running "sudo usermod -a -G localproxyusers $USER"
   and then restarting your login session.

node:fs:1708
  handleErrorFromBinding(ctx);
  ^

Error: EACCES: permission denied, unlink '/etc/localproxy/sites/temp-station.json'
    at Object.unlinkSync (node:fs:1708:3)
    at Object.<anonymous> (/mnt/d/Git/temp-monitor/server/node_modules/@kj800x/localproxy-client/lib/client.js:99:42)
    at step (/mnt/d/Git/temp-monitor/server/node_modules/@kj800x/localproxy-client/lib/client.js:44:23)
    at Object.next (/mnt/d/Git/temp-monitor/server/node_modules/@kj800x/localproxy-client/lib/client.js:25:53)
    at /mnt/d/Git/temp-monitor/server/node_modules/@kj800x/localproxy-client/lib/client.js:19:71
    at new Promise (<anonymous>)
    at __awaiter (/mnt/d/Git/temp-monitor/server/node_modules/@kj800x/localproxy-client/lib/client.js:15:12)
    at Object.register (/mnt/d/Git/temp-monitor/server/node_modules/@kj800x/localproxy-client/lib/client.js:89:12)
    at Server.<anonymous> (/mnt/d/Git/temp-monitor/server/lib/server.js:71:20)
    at Object.onceWrapper (node:events:513:28) {
  errno: -13,
  syscall: 'unlink',
  code: 'EACCES',
```

**Comment by kj800x** [comment]
Gotcha, sounds like if I can detect that the rest of LP isn't set up and skip that whole bit it should resolve it

**Comment by Abbondanzo** [comment]
Yeah that seems fair. FWIW, this change doesn't include any error handling for the response so if the API key is missing, it'll 500 rather than 401

**Comment by kj800x** [comment]
:smile: Thanks for motivating me to play around with the auth stuff! I've been meaning to dive deeper into figuring out how to set that up with express and graphql and all that. Some of the other projects that I want to work on will need to be internet facing but really should be authed more than no-auth, so this was good practice!

I did had a bit of a different vision on how I would add auth to personal projects, so I've pushed up some commits to set this up with JWTs and using context rather than mutation parameters. The flat secret key + parameter based approach would have worked fine here, but I try to keep the project setup the same for all my personal projects and I definitely would have wanted JWTs (or something else more powerful) in the other ones.

**Comment by kj800x** [comment]
Auth deployed!

```bash
curl 'http://apps.coolkev.com/temp/graphql' -H 'Accept-Encoding: gzip, deflate, br' -H 'Content-Type: application/json' -H 'Accept: application/json' -H 'Connection: keep-alive' -H 'DNT: 1' -H 'Origin: http://apps.coolkev.com' --data-binary '{"query":"mutation {\n  record(temperature: 1, humidity:1, date: 1) {\n    id\n  }\n}"}' --compressed
```

**Pull request merged**
