### PR TITLE
Update App.tsx

### PR DESCRIPTION
**Pull request by bent0b0x**
I had an idea for how to improve the app. What do you think?

### CODE REVIEW

**Review by kj800x — CHANGES_REQUESTED** [review]
Hey! Thanks for the contribution. I pulled it down and got a build failure though... I think you might have accidentally deleted the `App` component.

```
kevin@rayquaza:~/src/temp-monitor/ui$ bend build

> temp-monitor-ui@0.0.1 build /home/kevin/src/temp-monitor/ui
> localproxy-react-scripts build

Creating an optimized production build...
Failed to compile.

/home/kevin/src/temp-monitor/ui/src/App.tsx
TypeScript error in /home/kevin/src/temp-monitor/ui/src/App.tsx(undefined,undefined):
'App.tsx' cannot be compiled under '--isolatedModules' because it is considered a global script file. Add an import, export, or an empty 'export {}' statement to make it a module.  TS1208
```

**Comment by kj800x** [comment]
I think rather than just deleting the `App.tsx` file, it might be better to replace it with something like `export const App = () => null` which will still compile while achieving similar goals.

**Comment by bent0b0x** [comment]
> 

this looks like a good suggestion, let me test it out locally!

**Comment by bent0b0x** [comment]
> I think rather than just deleting the `App.tsx` file, it might be better to replace it with something like `export const App = () => null` which will still compile while achieving similar goals.

this looks like a good suggestion, let me test it out locally!

**Comment by bent0b0x** [comment]
PR feedback should be fixed by way of 957aca8

**Comment by bent0b0x** [comment]
PS it looks like there are some merge conflicts with this branch now. Can you please fix `master`?

**Comment by kj800x** [comment]
Yeah, gimme one sec, I think I can fix up this branch. Sorry bout the trouble

**Comment by kj800x** [comment]
@bent0b0x I had a bit of trouble with the merge but I think I came to something that worked eventually in 58218bd4a27388d50b08c7f4ee52e13f27c019c0? How's it look to you?

**Review by kj800x — APPROVED** [review]
LGTM with the latest changes

**Comment by bent0b0x** [comment]
Hello! This issue is still affecting us in production today. Please consider re-opening this PR

**Comment by kj800x** [comment]
Hey! Thanks for reaching out again. I'm so sorry to hear that this issue is still affecting you. Unfortunately, I am unable to reproduce the issue anymore. I think one of the recent commits might have resolved this? Are you still seeing this issue on the latest version?

**Pull request closed without merging**
